### ISSUE TITLE
Mi Home: Cloud: Login step 2 failed

### ISSUE THREAD

**Issue by semikor** [BOOMER74/node-red-contrib-mihome#16]
Похоже, Mi Home Cloud сделали 2х факторный вход (с подтверждением на мыло или СМС) и теперь node-red-contrib-mihome 1.1.1 выдает ошибку "Mi Home: Cloud: Login step 2 failed" и ничего не работает (((

**Comment by semikor** [comment]
Заработало
Прошу прощения за беспокойство!

**Comment by BOOMER74** [comment]
Такое периодически происходит. Чтобы все заработало нужно просто войти в аккаунт на сайте [Xiaomi](https://account.xiaomi.com).
