### ISSUE TITLE
Xiaomi Plant Monitor - hhcc.plantmonitor.v1

### ISSUE THREAD

**Issue by mrmaximas** [BOOMER74/node-red-contrib-mihome#17]
Здравствуйте!
Можно ли добавить поддержку этого устройства? 
https://home.miot-spec.com/spec/hhcc.plantmonitor.v1
Спасибо!

**Comment by BOOMER74** [comment]
Здравствуйте! К сожалению я пока что прекратил разработку этого пакета. Но для добавления нужно найти спецификацию для этого устройства, т.к. в node-mihome его нет, далее по аналогии с [этой нодой](https://github.com/BOOMER74/node-red-contrib-mihome/blob/master/nodes/mihome-th-monitor.js) добавить свою. Беглым поиском найти ее не удалось (в свое время я находил все на китайском, поэтому  придется еще переводить).

**Comment by mrmaximas** [comment]
> Здравствуйте! К сожалению я пока что прекратил разработку этого пакета. Но для добавления нужно найти спецификацию для этого устройства, т.к. в node-mihome его нет, далее по аналогии с [этой нодой](https://github.com/BOOMER74/node-red-contrib-mihome/blob/master/nodes/mihome-th-monitor.js) добавить свою. Беглым поиском найти ее не удалось (в свое время я находил все на китайском, поэтому придется еще переводить).

 спасибо.
 я уже решил проблему нодой exec, запускаю предварительно скомпиленную команду miot cloud get-props и разбираю ответ.
