### ISSUE TITLE
Flows stopped due to missing node types.  mihome-cloud

### ISSUE THREAD

**Issue by QuocurIQ** [BOOMER74/node-red-contrib-mihome#3]
**Common Info**

* Package version: 1.10
* Node name: mihome-cloud

**Describe the bug**
<img width="592" alt="Screen Shot 2021-05-01 at 22 27 04" src="https://user-images.githubusercontent.com/9988760/116794523-c7adb600-aacd-11eb-8164-5a6126589f81.png">
<img width="509" alt="Screen Shot 2021-05-01 at 22 20 58" src="https://user-images.githubusercontent.com/9988760/116794531-d300e180-aacd-11eb-908b-6ff296ff8504.png">

Fresh install of node-red 1.3.2. Installed node-red-contrib-mihome 1.1.0. After installation, the package looks weird in package manager. There is an ! [objectObject] warning just under the version, see attached screenshot.

After dropping the devices node in a flow, and configuring cloud credentials, an error message pops out on deployment:
Flows stopped due to missing node types.

mihome-cloud

The credentials in the configuration node are empty, each time I edit the configuration. Only the selected region stays.

**To Reproduce**

Steps/conditions to reproduce:

1. install 1.1.0 on node-red 1.3.2
2. drop devices node on flow connected to a debug and inject node
3. double click and add cloud configuration
4. enter valid mi cloud credentials and select region
5. update
6. deploy
7. Flows stopped due to missing node types.  mihome-cloud error message appears after deploying

**Expected behavior**

1. no warning in palette
2. no error message on deploying
3. no error message: "Error: node not deployed" shown when true is injected to the input
4. credentials are stored in the configuration node and visible when editting cofiguration

**Comment by BOOMER74** [comment]
Hello. I was recheck it twice on node-red 1.3.2 and 1.3.3. All nodes works as expected. Please read [settings note](https://github.com/BOOMER74/node-red-contrib-mihome#mihome-th-monitor) for `mihome-th-monitor`.

To be clear: first I setup flow like this (I already configure `mihome-cloud` for both nodes):

![1](https://user-images.githubusercontent.com/4272432/116920399-3f5d1b80-ac5b-11eb-984e-d5e4ee5bb92a.png)

It's return data like this (`mihome-th-monitor` return warning because have empty `did` field):

![2](https://user-images.githubusercontent.com/4272432/116920589-83502080-ac5b-11eb-99cf-f41948cdfab1.png)

Then I fill `did` field and get expected result:

![3](https://user-images.githubusercontent.com/4272432/116920725-ada1de00-ac5b-11eb-80cb-12c14baec677.png)

![4](https://user-images.githubusercontent.com/4272432/116920729-ae3a7480-ac5b-11eb-9de8-aa0278597a2e.png)

**Comment by BOOMER74** [comment]
Hello. I was recheck it twice on node-red 1.3.2 and 1.3.3. All nodes works as expected. Please read [settings note](https://github.com/BOOMER74/node-red-contrib-mihome#mihome-th-monitor) for `mihome-th-monitor`.

To be clear: first I setup flow like this (I already configure `mihome-cloud` for both nodes):

![1](https://user-images.githubusercontent.com/4272432/116920399-3f5d1b80-ac5b-11eb-984e-d5e4ee5bb92a.png)

It's return data like this (`mihome-th-monitor` return warning because have empty `did` field):

![2](https://user-images.githubusercontent.com/4272432/116920589-83502080-ac5b-11eb-99cf-f41948cdfab1.png)

Then I fill `did` field and get expected result:

![3](https://user-images.githubusercontent.com/4272432/117044585-45b0cd80-ad17-11eb-8472-b4455726d82b.png)

![4](https://user-images.githubusercontent.com/4272432/116920729-ae3a7480-ac5b-11eb-9de8-aa0278597a2e.png)

**Comment by QuocurIQ** [comment]
Hi.

For me the BT thermometers never return a value. They show as online, but I always get “Couldn’t get last temperature” ... What’s interesting is, that when I use the devices node, I don’t get the “prop” property in the payload.

Regards

Marek

**Comment by BOOMER74** [comment]
Hello.

Do you have some connected gateway, e.g. Mi Smart Home Hub (ZNDMWG02LM)? Because without gateway data from sensor not stored in cloud. This package designed to get data from cloud, not for directly reading data from device.

**Comment by QuocurIQ** [comment]
Hi.

This is my output from the "devices" node:

[
  {
    "did": “XXXXXXX”,
    "token": “XXXXXX”,
    "longitude": "0.00000000",
    "latitude": "0.00000000",
    "name": "Nizna Kamenica 205",
    "pid": "0",
    "localip": "10.95.1.109",
    "mac": "54:EF:44:CB:BD:41",
    "ssid": "SSID",
    "bssid": "DE:AD:BE:EF:A7:06",
    "parent_id": "",
    "parent_model": "",
    "show_mode": 1,
    "model": "lumi.gateway.mgl03",
    "adminFlag": 1,
    "shareFlag": 0,
    "permitLevel": 16,
    "isOnline": false,
    "desc": "Device offline ",
    "extra": {
      "isSetPincode": 0,
      "pincodeType": 0,
      "fw_version": "1.4.6_0043",
      "needVerifyCode": 0,
      "isPasswordEncrypt": 0
    },
    "uid": 6435630247,
    "pd_id": 1111,
    "password": "",
    "p2p_id": "",
    "rssi": -56,
    "family_id": 0,
    "reset_flag": 0
  },
  {
    "did": “XXXXXXX”,
    "token": “XXXXXXX”,
    "longitude": "0.00000000",
    "latitude": "0.00000000",
    "name": "SkladnaArchiv",
    "pid": "0",
    "localip": "172.16.70.158",
    "mac": "DE:AD:BE:EF:C1:B4",
    "ssid": "SSID2",
    "bssid": "DE:AD:BE:EF:5C:1B",
    "parent_id": "",
    "parent_model": "",
    "show_mode": 1,
    "model": "lumi.gateway.mgl03",
    "adminFlag": 1,
    "shareFlag": 0,
    "permitLevel": 16,
    "isOnline": true,
    "desc": "Device online ",
    "extra": {
      "isSetPincode": 0,
      "pincodeType": 0,
      "fw_version": "1.4.6_0043",
      "needVerifyCode": 0,
      "isPasswordEncrypt": 0
    },
    "uid": 6423634447,
    "pd_id": 1111,
    "password": "",
    "p2p_id": "",
    "rssi": -42,
    "family_id": 0,
    "reset_flag": 0
  },
  {
    "did": "blt.3.167XXXXX00",
    "token": “XXXXXXXX”,
    "longitude": "0.00000000",
    "latitude": "0.00000000",
    "name": "NK Office",
    "pid": "6",
    "localip": "99.121.35.104",
    "mac": "A4:C1:38:DE:AD:DA",
    "ssid": "",
    "bssid": "",
    "parent_id": "",
    "parent_model": "",
    "show_mode": 1,
    "model": "miaomiaoce.sensor_ht.t2",
    "adminFlag": 1,
    "shareFlag": 0,
    "permitLevel": 16,
    "isOnline": false,
    "desc": "",
    "extra": {
      "isSetPincode": 0,
      "pincodeType": 0,
      "fw_version": "1.0.0_0001",
      "needVerifyCode": 0,
      "isPasswordEncrypt": 0
    },
    "uid": 6435630447,
    "pd_id": 1371,
    "password": "",
    "p2p_id": "",
    "rssi": 0,
    "family_id": 0,
    "reset_flag": 0
  },
  {
    "did": "lumi.158FFFFFFFF26",
    "token": "",
    "longitude": "0.00000000",
    "latitude": "0.00000000",
    "name": "Skladna-sklad-roh",
    "pid": "3",
    "localip": "",
    "mac": "",
    "ssid": "SSID2",
    "bssid": "DE:AD:BE:EF:5C:1B",
    "parent_id": "XXXXXXX",
    "parent_model": "lumi.gateway.mgl03",
    "show_mode": 0,
    "model": "lumi.sensor_ht.v1",
    "adminFlag": 1,
    "shareFlag": 0,
    "permitLevel": 16,
    "isOnline": true,
    "desc": "Temperature: 20℃ Humidity:60% ",
    "extra": {
      "isSetPincode": 0,
      "pincodeType": 0
    },
    "prop": {
      "humidity": "6027",
      "temperature": "2005"
    },
    "uid": 6235830447,
    "pd_id": 98,
    "password": "",
    "p2p_id": "",
    "rssi": 0,
    "family_id": 0,
    "reset_flag": 0
  },
  {
    "did": "lumi.FFFFFFFF”,
    "token": "",
    "longitude": "0.00000000",
    "latitude": "0.00000000",
    "name": "Skladna-kancelaria-hore",
    "pid": "3",
    "localip": "",
    "mac": "",
    "ssid": "office",
    "bssid": "48:8F:5A:92:5C:1B",
    "parent_id": "XXXXXXX",
    "parent_model": "lumi.gateway.mgl03",
    "show_mode": 0,
    "model": "lumi.sensor_ht.v1",
    "adminFlag": 1,
    "shareFlag": 0,
    "permitLevel": 16,
    "isOnline": true,
    "desc": "Temperature: 24℃ Humidity:47% ",
    "extra": {
      "isSetPincode": 0,
      "pincodeType": 0
    },
    "prop": {
      "humidity": "4698",
      "temperature": "2396"
    },
    "uid": 6435630447,
    "pd_id": 98,
    "password": "",
    "p2p_id": "",
    "rssi": 0,
    "family_id": 0,
    "reset_flag": 0
  }
]


<img width="999" alt="Screen Shot 2021-06-12 at 05 23 11" src="https://user-images.githubusercontent.com/9988760/121763748-b7faa600-cb3e-11eb-912a-eeb5b5ef0771.png">


As you can see, I have 2 gateways, 2 zigbee sensors connected to one gateway and 1 BT sensor connected to the second gateway. Currently all 3 of them return "Mi Home: TH Monitor: cannot find last data for temperature or humidity" when I use the "TH monitor" node. The "devices" node would be OK for me, but the object from the BT sensor does not contain the "prop" property. You can see that in the output as well. What's also different for the BT sensor that it reports the Public IP address in the local IP property and it does not report parent_id and parent_model.

What would save my problem is:

If the "device" node would return parent and prop properties. 

Thanks

Regards

Marek

**Comment by BOOMER74** [comment]
Hi.

Firstly TH Monitor support only _Mi Temperature and Humidity Monitor 2_ (model `miaomiaoce.sensor_ht.t2` in devices result).

Secondly **Mi Home: TH Monitor: cannot find last data for temperature or humidity** means device have no stored data for 2 last days. As I see your `miaomiaoce.sensor_ht.t2` device is offline, so you need back it online first and then wait at least 10 minutes, before use device in `node-red`.

**Comment by Dabbadoeber** [comment]
Hi,

is there anyway you resolved this ?
i am getting the same message, and credentials are not saved.
