### ISSUE TITLE
Does not reconnect after Internet connection lost.

### ISSUE THREAD

**Issue by ghost** [BOOMER74/node-red-contrib-mihome#7]
Hi,

when the internet connectivity of nodered gets lost the node will no reconnect to the cloud automatically.
I need to restart the flows.

thanks

**Comment by BOOMER74** [comment]
Hello. Unfortunately, I haven't enough time to support package, but I have 24/7 working server with Node-RED at home and sometimes problems with internet will happens. However I haven't problems with Mi Home cloud connection even if internet will restored after long downtime. Actually connection to cloud managed by https://github.com/maxinminax/node-mihome and possibly better to create issue there.
