### ISSUE TITLE
Some TH Monitors stopped reporting data "cannot find last data for temperature or humidity"

### ISSUE THREAD

**Issue by mcbyte-it** [BOOMER74/node-red-contrib-mihome#9]
**Common Info**

* Package version: 1.1.1
* Node name: mihome-cloud

**Describe the bug**

I configured my 5 sensors to report to Google Assistant Sensor element, and at first they worked all fine, few days later I found that not all TH Monitors are giving out data anymore. They give an error message: 
`Mi Home: TH Monitor: cannot find last data for temperature or humidity`

![image](https://user-images.githubusercontent.com/3248742/182113802-94625117-11e4-4b7c-bcc8-7946297568de.png)

I tried deleting then re-pairing the sensor, nothing.
I even replaced the battery on one sensor to try, also nothing

The Devices node report all 5 sensors and the base Mi Gateway as online, and it is collecting and showing data on my phone.

**To Reproduce**

Steps/conditions to reproduce:
connect a TH Monitor with correct "did", nothing comes out

**Expected behavior**

TH Monitor extracts data for all connected sensors

**Additional context**

Worked for few days, then stopped

**Comment by BOOMER74** [comment]
Hello. I have checked all my devices and they are working properly. As I know TH Monitor 2 sending data only if they changed but don't believe they hasn't changing in more than 2 days (this interval is required to find the latest data). You can edit monitor logic to check the problem by changing this line https://github.com/BOOMER74/node-red-contrib-mihome/blob/master/nodes/mihome-th-monitor.js#L4 (by default this file is stored in user's home directory, e.g. `~/.node-red/node_modules/node-red-contrib-mihome/nodes/mihome-th-monitor.js`), change the "2" to higher value (e.g. 7) and restart Node-RED.
